"""empty message

Revision ID: 34cf3343cd5c
Revises: 21bc17386dfc
Create Date: 2023-08-31 16:12:51.143586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34cf3343cd5c'
down_revision = '21bc17386dfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('has_timeout', sa.Boolean(), nullable=False,
        server_default='false'))
    #op.alter_column('taskmodel', 'state',
    #           existing_type=postgresql.ENUM('NotStarted', 'Running', 'CompletedSuccess', 'CompletedError', 'ExceptionCaught', 'TimedOut', name='taskmodelstate'),
    #           type_=sa.Enum('NotStarted', 'Running', 'CompletedSuccess', 'CompletedError', 'ExceptionCaught', 'TimedOut', name='state'),
    #           existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('taskmodel', 'state',
    #           existing_type=sa.Enum('NotStarted', 'Running', 'CompletedSuccess', 'CompletedError', 'ExceptionCaught', 'TimedOut', name='state'),
    #           type_=postgresql.ENUM('NotStarted', 'Running', 'CompletedSuccess', 'CompletedError', 'ExceptionCaught', 'TimedOut', name='taskmodelstate'),
    #           existing_nullable=False)
    op.drop_column('package', 'has_timeout')
    # ### end Alembic commands ###
