"""empty message

Revision ID: b9754ef6f798
Revises: d9cdd3f0e114
Create Date: 2023-07-13 14:09:41.318437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9754ef6f798'
down_revision = 'd9cdd3f0e114'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versionpair', sa.Column('deps_download_state', sa.Enum('NotStarted', 'Running', 'CompletedSuccess', 'CompletedError', 'ExceptionCaught', 'TimedOut', name='state'), server_default='NotStarted', nullable=False))
    op.add_column('versionpair', sa.Column('ignore', sa.Boolean(), server_default='f', nullable=False))
    op.drop_column('versionpair', 'version_deps_download_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versionpair', sa.Column('version_deps_download_state', postgresql.ENUM('NotAttempted', 'Started', 'Failed', 'Succeeded', name='versionpairdependencystate'), server_default=sa.text("'NotAttempted'::versionpairdependencystate"), autoincrement=False, nullable=False))
    op.drop_column('versionpair', 'ignore')
    op.drop_column('versionpair', 'deps_download_state')
    # ### end Alembic commands ###
